namespace: remove-empty-ns-operator

resources:
  - manifests/namespace.yaml
  - manifests/rbac.yaml
  - manifests/deployment.yaml

configMapGenerator:
- name: remove-empty-ns-operator
  files:
  - settings.yaml

generatorOptions:
  labels:
    application: remove-empty-ns-operator
