apiVersion: apps/v1
kind: Deployment
metadata:
  name: remove-empty-ns-operator
  labels:
    application: remove-empty-ns-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: remove-empty-ns-operator
  template:
    metadata:
      labels:
        application: remove-empty-ns-operator
    spec:
      serviceAccountName: remove-empty-ns-operator
      containers:
        - name: remove-empty-ns-operator
          image: rgeraskin/remove-empty-ns-operator:1.1
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: remove-empty-ns-operator
