apiVersion: v1
kind: ServiceAccount
metadata:
  name: remove-empty-ns-operator
  labels:
    application: remove-empty-ns-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remove-empty-ns-operator
  labels:
    application: remove-empty-ns-operator
rules:
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch, patch]
  - apiGroups: [""]
    resources: [namespaces/status]
    verbs: [patch]
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # remove-empty-ns-operator
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [list]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remove-empty-ns-operator
  labels:
    application: remove-empty-ns-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remove-empty-ns-operator
subjects:
  - kind: ServiceAccount
    name: remove-empty-ns-operator
    namespace: remove-empty-ns-operator
